servuce:
  - docker
git:
  depth: 10
  submodules: true
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker build -t saidsef/alpine-jenkins-dockerfile:$TRAVIS_BRANCH .
  - docker push saidsef/alpine-jenkins-dockerfile
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
