language: shell

os: linux

dist: xenial

services:
  - docker 

git:
  depth: 10
  submodules: true
  
env:
  - BUILD_ID="$(git log --oneline --sparse --decorate --graph -n10)"

before_script:
  - docker pull jenkins/jenkins

script:
  - docker build --build-arg $BUILD_ID -t saidsef/alpine-jenkins-dockerfile:$TRAVIS_BRANCH .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push saidsef/alpine-jenkins-dockerfile

notifications:
  email: true
  on_success: always
  on_failure: change
