language: shell

os: linux

dist: xenial

services:
  - docker 

git:
  depth: 10
  submodules: true

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build --build-arg BUILD_ID="$(git log --oneline --sparse --decorate --graph -n10)" -t saidsef/alpine-jenkins-dockerfile:$TRAVIS_BRANCH .
  - docker push saidsef/alpine-jenkins-dockerfile

after_success:
  - echo "All done!"

notifications:
  email: true
  on_success: always
  on_failure: change
