---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins
  labels:
    name: jenkins
    app: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      server_tokens off;
spec:
  rules:
  - host: jenkins.saidsef.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 80