---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  labels:
    name: jenkins
    app: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      shareProcessNamespace: true
      initContainers:
        - name: jenkins-init
          image: busybox:latest
          command: ["sh", "-c", "chmod -R 777 /var/jenkins_home"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home
      containers:
        - name: jenkins-master
          image: saidsef/alpine-jenkins-dockerfile:master
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8080
              name: jenkins
            - protocol: TCP
              containerPort: 50000
              name: agent
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home/logs
              subPath: logs
            - name: jenkins-storage
              mountPath: /var/jenkins_home/jobs
              subPath: jobs
            - name: jenkins-storage
              mountPath: /var/jenkins_home/cache
              subPath: cache
            - name: jenkins-storage
              mountPath: /var/jenkins_home/jenkins-jobs
              subPath: jenkins-jobs
            - name: jenkins-storage
              mountPath: /var/jenkins_home/builds
              subPath: builds
            - name: jenkins-storage
              mountPath: /var/jenkins_home/secrets
              subPath: secrets
          livenessProbe:
            exec:
              command:
                - pgrep
                - java
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 2
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
                port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 2
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "900m"
              memory: "2048Mi"
      volumes:
        - name: jenkins-storage
          hostPath:
            path: /mnt/jenkins
            type: DirectoryOrCreate
