---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: cicd
  labels:
    name: jenkins
    app: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        name: app
        app: jenkins
    spec:
      containers:
        - image: saidsef/alpine-jenkins-dockerfile:latest
          name: jenkins
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8080
              name: jenkins
            - protocol: TCP
              containerPort: 5000
              name: agent
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home/logs
              subPath: logs
            - name: jenkins-storage
              mountPath: /var/jenkins_home/jobs
              subPath: jobs
            - name: jenkins-storage
              mountPath: /var/jenkins_home/cache
              subPath: cache
            - name: jenkins-storage
              mountPath: /var/jenkins_home/jenkins-jobs
              subPath: jenkins-jobs
            - name: jenkins-storage
              mountPath: /var/jenkins_home/builds
              subPath: builds
            - name: jenkins-storage
              mountPath: /var/jenkins_home/secrets
              subPath: secrets
      volumes:
        - name: jenkins-storage
          emptyDir: {}
