---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
    app: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins-master
  ports:
    - name: jenkins
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000