---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: cicd
  labels:
    name: jenkins
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: jenkins
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: agent
      port: 5000
      protocol: TCP
      targetPort: 5000